### PR TITLE
Bump up aws version

### PR DESCRIPTION
**Pull request by angulito**

### CODE REVIEW

**Comment by angulito** [comment]
Hi, thank you for the info - I already read about it, and I don't like so much that pattern but I think it's useful and easy way to deploy always the same versions that you test on your localhost.
But I've reverted the latest commit where I included the vendor folder and the gopkg files and now the PR is just for bumping up the version :)

**Comment by chicofranchico** [comment]
You're right. There might be breaking changes introduced with newer versions if you're using go get (and the aws-sdk is a very good example 😅)

I was checking out dep and you can now specify versions. Haven't tested myself though.

I've just made a new release v0.5.0 for latest aws-sdk-go-v1. I'll release this as v1.0.0.

Thanks!

**Comment by angulito** [comment]
cool! thank you for approving the PR - that's perfect.
let's hope the new way of handle go dependencies for the new `go` release is better (https://github.com/golang/go/wiki/vgo) :)

**Comment by chicofranchico** [comment]
Thanks for the help and the tip :)

**Pull request merged**
